### ISSUE TITLE
Styles no longer specific enough to work with default Reveal.js 3.0.0 theme

### ISSUE THREAD

**Issue by drzax** [nwinkler/reveal-highlight-themes#1]
It appears as though the changes introduced into Reveal at commit https://github.com/hakimel/reveal.js/commit/38301d57c547a349e2cc790996c1213720aed9d4 and released in 3.0.0 now render these highlight themes ineffective when using the default reveal theme.

The offending css starts at https://github.com/hakimel/reveal.js/blob/master/css/theme/template/theme.scss#L156

The specificity in these themes should be changed to include `.reveal`.

**Comment by drzax** [comment]
It also appears that Reveal/Highlight now uses a class prefix of `hljs-` by default which isn't present in any of the styles in this repo.

**Comment by nwinkler** [comment]
Thanks for the note - I'll take a look at this later.

**Comment by nwinkler** [comment]
It looks like you can just use the standard highlight.js themes without any modification. I created this project to transform the original highlight.js themes into the format that reveal was using at the time. It looks like reveal has changed the way they're using the syntax themes to the standard higlight.js format.

You should be able to simply drop the standard highlight.js themes into the reveal `lib/css` folder.

**Comment by drzax** [comment]
Great, thanks.

**Comment by janraasch** [comment]
Could you put this into the README? And then this issue may be closed I believe.

**Comment by nwinkler** [comment]
Thanks - I updated the readme.
